from odoo import models, fields

class AccountAccount(models.Model):
    _inherit = 'account.account'

    oman_format = fields.Selection([
        ('PS', 'Product Sales'),
        ('SR', 'Service Revenue'),
        ('CR', 'Contract Revenue'),
        ('RI', 'Rental Income'),
        ('CI', 'Commission Income'),
        ('II', 'Interest Income'),
        ('FEG', 'Foreign Exchange Gain'),
        ('GAD', 'Gain on Asset Disposal'),
        ('ONI', 'Other Non-operating Income'),
        ('DI_PL', 'Dividend Income'),
        ('MI', 'Miscellaneous Income'),
        ('OS', 'Opening Stock'),
        ('PURCHASE', 'Purchase'),
        ('DE', 'Direct Expenses'),
        ('CS', 'Closing Stock'),
        ('SW', 'Salaries and Wages'),
        ('SB', 'Staff Benefits'),
        ('AE', 'Accommodation Expense'),
        ('TE', 'Transport Expense'),
        ('RE', 'Rent Expense'),
        ('RM', 'Repairs and Maintenance'),
        ('VRM', 'Vehicle Repairs and Maintenance'),
        ('OAE', 'Office and Administrative Expenses'),
        ('AF', 'Audit Fees A/c'),
        ('LPF', 'Legal and Professional Fees'),
        ('INS', 'Insurance'),
        ('ITSE', 'IT and Software Expenses'),
        ('MSE', 'Marketing and Selling Expenses'),
        ('TC', 'Travel and Conveyance'),
        ('IME', 'Internet & Mobile Expenses'),
        ('OE', 'Other Expenses'),
        ('IL', 'Interest on Loans'),
        ('BC', 'Bank Charges'),
        ('PPE', 'Property, Plant & Equipment'),
        ('CWIP', 'Capital Work in Progress'),
        ('IP', 'Investment Property'),
        ('ROU', 'Right of Use Assets'),
        ('IA', 'Intangible Assets'),
        ('GW', 'Goodwill'),
        ('LTI', 'Long-term Investments'),
        ('DTA', 'Deferred Tax Asset'),
        ('LTA', 'Long-term Advances'),
        ('DI_BS', 'Deferred Interest'),
        ('ONCA', 'Other Non-Current Assets'),
        ('INV', 'Inventories'),
        ('WIP', 'Work in Progress'),
        ('TR', 'Trade Receivables'),
        ('CONTR_ASSET', 'Contract Assets'),
        ('RET_REC', 'Retention Receivable'),
        ('OTH_REC', 'Other Receivables'),
        ('STI', 'Short-term Investments'),
        ('CASH_HAND', 'Cash in Hand'),
        ('BANK_ACC', 'Bank Accounts'),
        ('FD', 'Fixed Deposits'),
        ('PREP', 'Prepayments'),
        ('ACCR_INC', 'Accrued Income'),
        ('VAT_REC', 'VAT Receivable'),
        ('STA', 'Short-term Advances'),
        ('OCA', 'Other Current Assets'),
        ('SHARE_CAP', 'Share Capital'),
        ('MCA', 'Members Current Account'),
        ('STR', 'Statutory Reserve'),
        ('GR', 'General Reserve'),
        ('FVR', 'Fair Value Reserve'),
        ('ACC_PROFIT_LOSS', 'Accumulated Profit/(loss)'),
        ('LTB', 'Long-term Borrowings'),
        ('LL', 'Lease Liabilities'),
        ('ETB', 'Employee Terminal Benefit'),
        ('DTL', 'Deferred Tax Liability'),
        ('LTP', 'Long-term Provisions'),
        ('ONCL', 'Other Non-Current Liabilities'),
        ('TP', 'Trade Payables'),
        ('CONTR_LIAB', 'Contract Liabilities'),
        ('RET_PAY', 'Retention Payable'),
        ('ACCR_EXP', 'Accrued Expenses'),
        ('STB', 'Short-term Borrowings'),
        ('CPLTD', 'Current Portion of Long-term Debt'),
        ('VAT_PAY', 'VAT Payable'),
        ('WHT_PAY', 'Withholding / Other Taxes Payable'),
        ('PAYROLL_PAY', 'Payroll Payables'),
        ('DIV_PAY', 'Dividends Payable'),
        ('OCL', 'Other Current Liabilities'),
    ], string='Oman Format Mapping', help='Used to map this account to a specific line in Oman format reports.')
