from odoo import models, fields

class AccountAccount(models.Model):
    _inherit = 'account.account'

    oman_format = fields.Selection([
        ('PS', 'Product Sales'),
        ('SR', 'Service Revenue'),
        ('CR', 'Contract Revenue'),
        ('RI', 'Rental Income'),
        ('CI', 'Commission Income'),
        ('II', 'Interest Income'),
        ('FEG', 'Foreign Exchange Gain'),
        ('GAD', 'Gain on Asset Disposal'),
        ('ONI', 'Other Non-operating Income'),
        ('DI_PL', 'Dividend Income'),
        ('MI', 'Miscellaneous Income'),
        ('OS', 'Opening Stock'),
        ('PURCHASE', 'Purchase'),
        ('DE', 'Direct Expenses'),
        ('CS', 'Closing Stock'),
        ('SW', 'Salaries and Wages'),
        ('SB', 'Staff Benefits'),
        ('AE', 'Accommodation Expense'),
        ('TE', 'Transport Expense'),
        ('RE', 'Rent Expense'),
        ('RM', 'Repairs and Maintenance'),
        ('VRM', 'Vehicle Repairs and Maintenance'),
        ('OAE', 'Office and Administrative Expenses'),
        ('AF', 'Audit Fees'),
        ('LPF', 'Legal and Professional Fees'),
        ('INS', 'Insurance'),
        ('ITSE', 'IT and Software Expenses'),
        ('MSE', 'Marketing and Selling Expenses'),
        ('TC', 'Travel and Conveyance'),
        ('IME', 'Internet & Mobile Expenses'),
        ('OE', 'Other Expenses'),
        ('IL', 'Interest on Loans'),
        ('BC', 'Bank Charges'),
        ('PPE', 'Property, Plant & Equipment'),
        ('CWIP', 'Capital Work in Progress'),
        ('IP', 'Investment Property'),
        ('ROU', 'Right of Use Assets'),
        ('IA', 'Intangible Assets'),
        ('GW', 'Goodwill'),
        ('LTI', 'Long-term Investments'),
        ('DTA', 'Deferred Tax Asset'),
        ('LTA', 'Long-term Advances'),
        ('DI_BS', 'Deferred Interest'),
        ('ONCA', 'Other Non-Current Assets'),
        ('INV', 'Inventories'),
        ('WIP', 'Work in Progress'),
        ('TR', 'Trade Receivables'),
    ], string='Oman Format Mapping', help='Used to map this account to a specific line in Oman format reports.')
